import os
import math
import datetime as dt
import torch
from torch.nn import functional as F
from typing import TYPE_CHECKING, Optional
from jyutvoice.utils.model import (
    sequence_mask,
    generate_path,
)
from jyutvoice.utils.mask import make_pad_mask
import jyutvoice.utils.monotonic_align as monotonic_align
from jyutvoice.models.baselightningmodule import BaseLightningClass
from jyutvoice.models.duration_predictor import duration_loss

if TYPE_CHECKING:
    from jyutvoice.models.text_encoder import TextEncoder
    from jyutvoice.flow.flow_matching import CausalConditionalCFM
    from jyutvoice.models.duration_predictor import DurationPredictor
    from jyutvoice.models.slp import SpeechLengthPredictor


class JyutVoiceTTS(BaseLightningClass):
    def __init__(
        self,
        encoder: "TextEncoder",
        decoder: Optional["CausalConditionalCFM"],
        dp: "DurationPredictor",
        output_size=80,
        spk_embed_dim=192,
        freeze_encoder=False,
        freeze_decoder=False,
        optimizer=None,
        scheduler=None,
        warmup_steps=100,
        n_frame_per_class=10,
    ):
        super().__init__()

        self.save_hyperparameters(logger=False)

        self.encoder = encoder
        self.decoder = decoder
        self.n_feats = encoder.n_feats
        self.spk_embed_affine_layer = torch.nn.Linear(spk_embed_dim, output_size)
        self.output_size = output_size
        self.freeze_decoder = freeze_decoder
        self.freeze_encoder = freeze_encoder
        self.dp = dp
        self.n_frame_per_class = n_frame_per_class

    @torch.inference_mode()
    def synthesise(
        self,
        x,
        x_lengths,
        lang,
        tone,
        word_pos,
        syllable_pos,
        spk_embed,
        prompt_feat,
        prompt_h=None,
        n_timesteps=10,
        temperature=1.0,
        length_scale=1.0,
    ):
        """
        Generates mel-spectrogram from text. Returns:
            1. encoder outputs
            2. decoder outputs
            3. generated alignment

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
                shape: (batch_size,)
            lang (torch.Tensor): language tokens.
                shape: (batch_size, max_text_length)
            tone (torch.Tensor): tone tokens.
                shape: (batch_size, max_text_length)
            word_pos (torch.Tensor): word position tokens.
                shape: (batch_size, max_text_length)
            syllable_pos (torch.Tensor): syllable position tokens.
                shape: (batch_size, max_text_length)
            prompt_feat (torch.Tensor): prompt mel-spectrogram for conditioning.
                shape: (batch_size, max_prompt_length, n_feats)
            prompt_h (torch.Tensor): prompt hidden states for conditioning.
                shape: (batch_size, max_prompt_length, n_feats)
            spk_embed (torch.Tensor): speaker embeddings.
                shape: (batch_size, spk_emb_dim)
            n_timesteps (int): number of steps to use for reverse diffusion in decoder.
            temperature (float, optional): controls variance of diffusion. Defaults to 1.0.
            length_scale (float, optional): controls speech pace.
                Increase value to slow down generated speech and vice versa. Defaults to 1.0.

        Returns:
            dict: {
                "encoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Average mel spectrogram generated by the encoder
                "decoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Refined mel spectrogram improved by the CFM
                "attn": torch.Tensor, shape: (batch_size, max_text_length, max_mel_length),
                # Alignment map between text and mel spectrogram
                "mel": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Denormalized mel spectrogram
                "mel_lengths": torch.Tensor, shape: (batch_size,),
                # Lengths of mel spectrograms
                "rtf": float,
                # Real-time factor
            }
        """
        # For RTF computation
        t = dt.datetime.now()

        # Project speaker embedding for FM conditioning
        spk_embed = F.normalize(spk_embed, dim=1)
        c = self.spk_embed_affine_layer(spk_embed)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        x_enc, mu_x, x_mask = self.encoder(
            x, x_lengths, lang, tone, word_pos, syllable_pos, spk_embed
        )  # x_enc = [B, n_feats, T_text], mu_x = [1, n_mel, T_text], x_mask = [1, 1, T_text]

        from jyutvoice.models.slp import SpeechLengthPredictor

        # Handle duration prediction
        if isinstance(self.dp, SpeechLengthPredictor):
            # If DP is an SLP, it predicts total length
            slp_out = self.dp(
                x,
                x_mask,
                lang=lang,
                tone=tone,
                word_pos=word_pos,
                syllable_pos=syllable_pos,
                spk_embed=spk_embed,
            )
            if slp_out.dim() > 1 and slp_out.shape[-1] > 1:  # CE logits
                total_length = (
                    torch.argmax(slp_out, dim=-1).float() * self.n_frame_per_class
                )
            else:  # L1 scalar
                total_length = slp_out.float()

            # Ensure total_length is (B, 1)
            if total_length.dim() == 1:
                total_length = total_length.unsqueeze(-1)

            # Uniform distribution across phonemes scaled to SLP prediction
            avg_dur = total_length / (x_lengths.float().unsqueeze(-1) + 1e-6)
            w = avg_dur.unsqueeze(-1).expand(-1, 1, x_mask.size(2)) * x_mask
        else:
            # Standard DurationPredictor
            logw = self.dp(x_enc, x_mask)  # B, 1, T_text
            w = torch.exp(logw) * x_mask  # B, 1, T_text

        w_ceil = torch.ceil(w) * length_scale  # B, 1, T_text
        y_lengths = torch.clamp_min(torch.sum(w_ceil, [1, 2]), 1).long()  # B,
        y_max_length = y_lengths.max()

        # Using obtained durations `w` construct alignment map `attn`
        y_mask = sequence_mask(y_lengths, y_max_length).unsqueeze(1).to(x_mask.dtype)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)
        attn = generate_path(w_ceil.squeeze(1), attn_mask.squeeze(1)).unsqueeze(1)

        # Align encoded text and get mu_y
        mu_y = torch.matmul(
            attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2)
        ).transpose(
            1, 2
        )  # B, n_feats, T_mel
        encoder_outputs = mu_y[:, :, :y_max_length]

        # Enforce batch_size=1 for inference (decoder requirement)
        batch_size = x.size(0)
        if batch_size != 1:
            raise ValueError(
                f"synthesise() requires batch_size=1, got batch_size={batch_size}. "
                "Please pass one sample at a time."
            )

        if prompt_feat is not None and prompt_h is not None:
            mu_y = torch.cat([prompt_h.transpose(1, 2), mu_y], dim=2)
            n_mel = prompt_feat.shape[2]
            mel_len1, mel_len2 = (
                prompt_feat.shape[1],
                mu_y.shape[2] - prompt_feat.shape[1],
            )
            conds = torch.zeros([1, mel_len1 + mel_len2, n_mel], device=x.device).to(
                mu_y.dtype
            )
            conds[:, :mel_len1] = prompt_feat
            conds = conds.transpose(1, 2)

            mask = (~make_pad_mask(torch.tensor([mel_len1 + mel_len2]))).to(conds.dtype)
        else:
            mel_len1 = 0
            conds = torch.zeros_like(mu_y).to(mu_y.dtype)
            mask = (~make_pad_mask(y_lengths)).to(mu_y.dtype)

        decoder_outputs = None
        rtf = None

        if self.decoder is not None:
            # Decoder forward pass
            decoder_outputs, _ = self.decoder(
                mu=mu_y,
                mask=mask.unsqueeze(1),
                spks=c,
                cond=conds,
                n_timesteps=n_timesteps,
                temperature=temperature,
                streaming=False,
            )
            decoder_outputs = decoder_outputs[:, :, mel_len1:]

            t = (dt.datetime.now() - t).total_seconds()
            rtf = t * 24000 / (decoder_outputs.shape[-1] * 480)

        return {
            "encoder_outputs": encoder_outputs,
            "decoder_outputs": decoder_outputs,
            "attn": attn,
            "mel": decoder_outputs,
            "mel_lengths": y_lengths,
            "rtf": rtf,
        }

    def forward(
        self,
        x,
        x_lengths,
        y,
        y_lengths,
        lang,
        tone,
        word_pos,
        syllable_pos,
        spk_embed,
        decoder_h,
    ):
        """
        Computes 3 losses:
            1. duration loss: loss between predicted token durations and those extracted by Monotonic Alignment Search (MAS).
            2. prior loss: the loss between the hidden state of CosyVoice2's flow encoder and the output of the text encoder.
            3. flow matching loss: loss between mel-spectrogram and decoder outputs.

        Args:
            x: Input token IDs (B, T_text)
            x_lengths: Lengths of input token sequences (B,)
            y: Target mel-spectrograms (B, n_mel_channels, T_mel)
            y_lengths: Lengths of target mel-spectrograms (B,)
            lang: Language information (B, T_text)
            tone: Tone information (B, T_text)
            word_pos: Word position information (B, T_text)
            syllable_pos: Syllable position information (B, T_text)
            spk_embed: Speaker embedding (B, spk_embed_dim)
            decoder_h: Hidden states from the flow encoder of CosyVoice2 (B, T_mel, n_feats)
            durations: Optional ground truth durations for teacher forcing
        """
        # xvec projection
        spk_embed = F.normalize(spk_embed, dim=1)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        # compute style conditioning
        x, mu_x, x_mask = self.encoder(
            x, x_lengths, lang, tone, word_pos, syllable_pos, spk_embed
        )  # x = [B, n_feats, T_text], mu_x = [1, n_feats, T_text], x_mask = [1, 1, T_text]
        logw = self.dp(x, x_mask)  # B, 1, T_text

        y_max_length = decoder_h.shape[1]

        y_mask = sequence_mask(y_lengths, y_max_length).unsqueeze(1).to(x_mask)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)

        # Use MAS to find most likely alignment `attn` between text tokens and decoder_h
        # The text encoder is trained to map text → decoder_h space, so align to decoder_h
        with torch.no_grad():
            const = -0.5 * math.log(2 * math.pi) * self.n_feats
            factor = -0.5 * torch.ones(mu_x.shape, dtype=mu_x.dtype, device=mu_x.device)
            # Use decoder_h (flow encoder hidden states) for alignment computation
            # decoder_h: (batch, T_mel, n_feats) → transpose to (batch, n_feats, T_mel)
            h = decoder_h.transpose(1, 2)
            h_square = torch.matmul(factor.transpose(1, 2), (h**2))
            h_mu_double = torch.matmul(2.0 * (factor * mu_x).transpose(1, 2), h)
            mu_square = torch.sum(factor * (mu_x**2), 1).unsqueeze(-1)
            log_prior = h_square - h_mu_double + mu_square + const

            attn = monotonic_align.maximum_path(log_prior, attn_mask.squeeze(1))
            attn = attn.detach()  # b, T_text, T_mel

        # Compute loss between predicted log-scaled durations and those obtained from MAS
        # refered to as prior loss in the paper
        logw_ = torch.log(1e-8 + torch.sum(attn.unsqueeze(1), -1)) * x_mask
        dur_loss = duration_loss(logw, logw_, x_lengths)

        # Align encoded text with mel-spectrogram and get mu_y segment
        # attn: [b, T_text, T_mel] -> [b, T_mel, T_text] x mu_x: [b, n_feats, T_text]
        mu_y = torch.matmul(
            attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2)
        )  # (B, T_mel, n_feats)
        mu_y = mu_y.transpose(1, 2)

        # Compute the prior loss: MSE between aligned encoder representations
        # The prior loss trains the text encoder to match the frozen flow encoder representations
        # Compute prior loss comparing aligned representations
        prior_loss = torch.sum(
            0.5
            * ((decoder_h.transpose(1, 2) - mu_y) ** 2 + math.log(2 * math.pi))
            * y_mask
        )
        prior_loss = prior_loss / (torch.sum(y_mask) * self.n_feats)

        return dur_loss, prior_loss, attn
